#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteEscritorio
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDCVFormal")]
	public partial class EscritorioDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTCorreo(TCorreo instance);
    partial void UpdateTCorreo(TCorreo instance);
    partial void DeleteTCorreo(TCorreo instance);
    partial void InsertTHabilidad(THabilidad instance);
    partial void UpdateTHabilidad(THabilidad instance);
    partial void DeleteTHabilidad(THabilidad instance);
    partial void InsertTCuenta(TCuenta instance);
    partial void UpdateTCuenta(TCuenta instance);
    partial void DeleteTCuenta(TCuenta instance);
    partial void InsertTEstudio(TEstudio instance);
    partial void UpdateTEstudio(TEstudio instance);
    partial void DeleteTEstudio(TEstudio instance);
    partial void InsertTTelefono(TTelefono instance);
    partial void UpdateTTelefono(TTelefono instance);
    partial void DeleteTTelefono(TTelefono instance);
    partial void InsertTInfo(TInfo instance);
    partial void UpdateTInfo(TInfo instance);
    partial void DeleteTInfo(TInfo instance);
    partial void InsertTRedSocial(TRedSocial instance);
    partial void UpdateTRedSocial(TRedSocial instance);
    partial void DeleteTRedSocial(TRedSocial instance);
    partial void InsertTUbigeo(TUbigeo instance);
    partial void UpdateTUbigeo(TUbigeo instance);
    partial void DeleteTUbigeo(TUbigeo instance);
    partial void InsertTTrabajo(TTrabajo instance);
    partial void UpdateTTrabajo(TTrabajo instance);
    partial void DeleteTTrabajo(TTrabajo instance);
    #endregion
		
		public EscritorioDataContext() : 
				base(global::ClienteEscritorio.Properties.Settings.Default.BDCVFormalConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EscritorioDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscritorioDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscritorioDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EscritorioDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TCorreo> TCorreo
		{
			get
			{
				return this.GetTable<TCorreo>();
			}
		}
		
		public System.Data.Linq.Table<THabilidad> THabilidad
		{
			get
			{
				return this.GetTable<THabilidad>();
			}
		}
		
		public System.Data.Linq.Table<TCuenta> TCuenta
		{
			get
			{
				return this.GetTable<TCuenta>();
			}
		}
		
		public System.Data.Linq.Table<TEstudio> TEstudio
		{
			get
			{
				return this.GetTable<TEstudio>();
			}
		}
		
		public System.Data.Linq.Table<TTelefono> TTelefono
		{
			get
			{
				return this.GetTable<TTelefono>();
			}
		}
		
		public System.Data.Linq.Table<TInfo> TInfo
		{
			get
			{
				return this.GetTable<TInfo>();
			}
		}
		
		public System.Data.Linq.Table<TRedSocial> TRedSocial
		{
			get
			{
				return this.GetTable<TRedSocial>();
			}
		}
		
		public System.Data.Linq.Table<TUbigeo> TUbigeo
		{
			get
			{
				return this.GetTable<TUbigeo>();
			}
		}
		
		public System.Data.Linq.Table<TTrabajo> TTrabajo
		{
			get
			{
				return this.GetTable<TTrabajo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCorreo")]
	public partial class TCorreo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodCorreo;
		
		private System.Nullable<char> _Vision;
		
		private string _Tipo;
		
		private string _Correo;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCorreoChanging(int value);
    partial void OnCodCorreoChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TCorreo()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCorreo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodCorreo
		{
			get
			{
				return this._CodCorreo;
			}
			set
			{
				if ((this._CodCorreo != value))
				{
					this.OnCodCorreoChanging(value);
					this.SendPropertyChanging();
					this._CodCorreo = value;
					this.SendPropertyChanged("CodCorreo");
					this.OnCodCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(200)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(200)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TCorreo", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TCorreo.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TCorreo.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THabilidad")]
	public partial class THabilidad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodHabilidad;
		
		private System.Nullable<char> _Vision;
		
		private string _Nombre;
		
		private string _Nivel;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodHabilidadChanging(int value);
    partial void OnCodHabilidadChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnNivelChanging(string value);
    partial void OnNivelChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public THabilidad()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodHabilidad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodHabilidad
		{
			get
			{
				return this._CodHabilidad;
			}
			set
			{
				if ((this._CodHabilidad != value))
				{
					this.OnCodHabilidadChanging(value);
					this.SendPropertyChanging();
					this._CodHabilidad = value;
					this.SendPropertyChanged("CodHabilidad");
					this.OnCodHabilidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nivel", DbType="VarChar(200)")]
		public string Nivel
		{
			get
			{
				return this._Nivel;
			}
			set
			{
				if ((this._Nivel != value))
				{
					this.OnNivelChanging(value);
					this.SendPropertyChanging();
					this._Nivel = value;
					this.SendPropertyChanged("Nivel");
					this.OnNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_THabilidad", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.THabilidad.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.THabilidad.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TCuenta")]
	public partial class TCuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodCuenta;
		
		private string _CorreoSeguro;
		
		private string _Usuario;
		
		private System.Data.Linq.Binary _Contrasena;
		
		private char _Estado;
		
		private System.DateTime _FechaRegistro;
		
		private string _Seudonimo;
		
		private string _Llave;
		
		private EntitySet<TCorreo> _TCorreo;
		
		private EntitySet<THabilidad> _THabilidad;
		
		private EntitySet<TEstudio> _TEstudio;
		
		private EntitySet<TTelefono> _TTelefono;
		
		private EntitySet<TInfo> _TInfo;
		
		private EntitySet<TRedSocial> _TRedSocial;
		
		private EntitySet<TTrabajo> _TTrabajo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    partial void OnCorreoSeguroChanging(string value);
    partial void OnCorreoSeguroChanged();
    partial void OnUsuarioChanging(string value);
    partial void OnUsuarioChanged();
    partial void OnContrasenaChanging(System.Data.Linq.Binary value);
    partial void OnContrasenaChanged();
    partial void OnEstadoChanging(char value);
    partial void OnEstadoChanged();
    partial void OnFechaRegistroChanging(System.DateTime value);
    partial void OnFechaRegistroChanged();
    partial void OnSeudonimoChanging(string value);
    partial void OnSeudonimoChanged();
    partial void OnLlaveChanging(string value);
    partial void OnLlaveChanged();
    #endregion
		
		public TCuenta()
		{
			this._TCorreo = new EntitySet<TCorreo>(new Action<TCorreo>(this.attach_TCorreo), new Action<TCorreo>(this.detach_TCorreo));
			this._THabilidad = new EntitySet<THabilidad>(new Action<THabilidad>(this.attach_THabilidad), new Action<THabilidad>(this.detach_THabilidad));
			this._TEstudio = new EntitySet<TEstudio>(new Action<TEstudio>(this.attach_TEstudio), new Action<TEstudio>(this.detach_TEstudio));
			this._TTelefono = new EntitySet<TTelefono>(new Action<TTelefono>(this.attach_TTelefono), new Action<TTelefono>(this.detach_TTelefono));
			this._TInfo = new EntitySet<TInfo>(new Action<TInfo>(this.attach_TInfo), new Action<TInfo>(this.detach_TInfo));
			this._TRedSocial = new EntitySet<TRedSocial>(new Action<TRedSocial>(this.attach_TRedSocial), new Action<TRedSocial>(this.detach_TRedSocial));
			this._TTrabajo = new EntitySet<TTrabajo>(new Action<TTrabajo>(this.attach_TTrabajo), new Action<TTrabajo>(this.detach_TTrabajo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorreoSeguro", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CorreoSeguro
		{
			get
			{
				return this._CorreoSeguro;
			}
			set
			{
				if ((this._CorreoSeguro != value))
				{
					this.OnCorreoSeguroChanging(value);
					this.SendPropertyChanging();
					this._CorreoSeguro = value;
					this.SendPropertyChanged("CorreoSeguro");
					this.OnCorreoSeguroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this.OnUsuarioChanging(value);
					this.SendPropertyChanging();
					this._Usuario = value;
					this.SendPropertyChanged("Usuario");
					this.OnUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarBinary(200) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this.OnContrasenaChanging(value);
					this.SendPropertyChanging();
					this._Contrasena = value;
					this.SendPropertyChanged("Contrasena");
					this.OnContrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Char(1) NOT NULL")]
		public char Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="Date NOT NULL")]
		public System.DateTime FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seudonimo", DbType="VarChar(100)")]
		public string Seudonimo
		{
			get
			{
				return this._Seudonimo;
			}
			set
			{
				if ((this._Seudonimo != value))
				{
					this.OnSeudonimoChanging(value);
					this.SendPropertyChanging();
					this._Seudonimo = value;
					this.SendPropertyChanged("Seudonimo");
					this.OnSeudonimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Llave", DbType="VarChar(100)")]
		public string Llave
		{
			get
			{
				return this._Llave;
			}
			set
			{
				if ((this._Llave != value))
				{
					this.OnLlaveChanging(value);
					this.SendPropertyChanging();
					this._Llave = value;
					this.SendPropertyChanged("Llave");
					this.OnLlaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TCorreo", Storage="_TCorreo", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TCorreo> TCorreo
		{
			get
			{
				return this._TCorreo;
			}
			set
			{
				this._TCorreo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_THabilidad", Storage="_THabilidad", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<THabilidad> THabilidad
		{
			get
			{
				return this._THabilidad;
			}
			set
			{
				this._THabilidad.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TEstudio", Storage="_TEstudio", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TEstudio> TEstudio
		{
			get
			{
				return this._TEstudio;
			}
			set
			{
				this._TEstudio.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TTelefono", Storage="_TTelefono", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TTelefono> TTelefono
		{
			get
			{
				return this._TTelefono;
			}
			set
			{
				this._TTelefono.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TInfo", Storage="_TInfo", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TInfo> TInfo
		{
			get
			{
				return this._TInfo;
			}
			set
			{
				this._TInfo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TRedSocial", Storage="_TRedSocial", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TRedSocial> TRedSocial
		{
			get
			{
				return this._TRedSocial;
			}
			set
			{
				this._TRedSocial.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TTrabajo", Storage="_TTrabajo", ThisKey="CodCuenta", OtherKey="CodCuenta")]
		public EntitySet<TTrabajo> TTrabajo
		{
			get
			{
				return this._TTrabajo;
			}
			set
			{
				this._TTrabajo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TCorreo(TCorreo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TCorreo(TCorreo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_THabilidad(THabilidad entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_THabilidad(THabilidad entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_TEstudio(TEstudio entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TEstudio(TEstudio entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_TTelefono(TTelefono entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TTelefono(TTelefono entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_TInfo(TInfo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TInfo(TInfo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_TRedSocial(TRedSocial entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TRedSocial(TRedSocial entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
		
		private void attach_TTrabajo(TTrabajo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = this;
		}
		
		private void detach_TTrabajo(TTrabajo entity)
		{
			this.SendPropertyChanging();
			entity.TCuenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TEstudio")]
	public partial class TEstudio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodEstudio;
		
		private System.Nullable<char> _Vision;
		
		private string _Institucion;
		
		private string _Facultad;
		
		private string _Carrera;
		
		private System.Nullable<System.DateTime> _Inicio;
		
		private System.Nullable<System.DateTime> _Fin;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodEstudioChanging(int value);
    partial void OnCodEstudioChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnInstitucionChanging(string value);
    partial void OnInstitucionChanged();
    partial void OnFacultadChanging(string value);
    partial void OnFacultadChanged();
    partial void OnCarreraChanging(string value);
    partial void OnCarreraChanged();
    partial void OnInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnInicioChanged();
    partial void OnFinChanging(System.Nullable<System.DateTime> value);
    partial void OnFinChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TEstudio()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodEstudio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodEstudio
		{
			get
			{
				return this._CodEstudio;
			}
			set
			{
				if ((this._CodEstudio != value))
				{
					this.OnCodEstudioChanging(value);
					this.SendPropertyChanging();
					this._CodEstudio = value;
					this.SendPropertyChanged("CodEstudio");
					this.OnCodEstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Institucion", DbType="VarChar(200)")]
		public string Institucion
		{
			get
			{
				return this._Institucion;
			}
			set
			{
				if ((this._Institucion != value))
				{
					this.OnInstitucionChanging(value);
					this.SendPropertyChanging();
					this._Institucion = value;
					this.SendPropertyChanged("Institucion");
					this.OnInstitucionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Facultad", DbType="VarChar(200)")]
		public string Facultad
		{
			get
			{
				return this._Facultad;
			}
			set
			{
				if ((this._Facultad != value))
				{
					this.OnFacultadChanging(value);
					this.SendPropertyChanging();
					this._Facultad = value;
					this.SendPropertyChanged("Facultad");
					this.OnFacultadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Carrera", DbType="VarChar(200)")]
		public string Carrera
		{
			get
			{
				return this._Carrera;
			}
			set
			{
				if ((this._Carrera != value))
				{
					this.OnCarreraChanging(value);
					this.SendPropertyChanging();
					this._Carrera = value;
					this.SendPropertyChanged("Carrera");
					this.OnCarreraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio", DbType="Date")]
		public System.Nullable<System.DateTime> Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this.OnInicioChanging(value);
					this.SendPropertyChanging();
					this._Inicio = value;
					this.SendPropertyChanged("Inicio");
					this.OnInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fin", DbType="Date")]
		public System.Nullable<System.DateTime> Fin
		{
			get
			{
				return this._Fin;
			}
			set
			{
				if ((this._Fin != value))
				{
					this.OnFinChanging(value);
					this.SendPropertyChanging();
					this._Fin = value;
					this.SendPropertyChanged("Fin");
					this.OnFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TEstudio", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TEstudio.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TEstudio.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTelefono")]
	public partial class TTelefono : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodTelefono;
		
		private System.Nullable<char> _Vision;
		
		private string _Tipo;
		
		private string _Numero;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodTelefonoChanging(int value);
    partial void OnCodTelefonoChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnNumeroChanging(string value);
    partial void OnNumeroChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TTelefono()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTelefono", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodTelefono
		{
			get
			{
				return this._CodTelefono;
			}
			set
			{
				if ((this._CodTelefono != value))
				{
					this.OnCodTelefonoChanging(value);
					this.SendPropertyChanging();
					this._CodTelefono = value;
					this.SendPropertyChanged("CodTelefono");
					this.OnCodTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Numero", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Numero
		{
			get
			{
				return this._Numero;
			}
			set
			{
				if ((this._Numero != value))
				{
					this.OnNumeroChanging(value);
					this.SendPropertyChanging();
					this._Numero = value;
					this.SendPropertyChanged("Numero");
					this.OnNumeroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TTelefono", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TTelefono.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TTelefono.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TInfo")]
	public partial class TInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodInfo;
		
		private string _Apellidos;
		
		private string _Nombres;
		
		private System.Nullable<System.DateTime> _Nacimiento;
		
		private System.Nullable<char> _Sexo;
		
		private System.Nullable<char> _EstadoCivil;
		
		private string _DNI;
		
		private string _Direccion;
		
		private string _Informacion;
		
		private System.Data.Linq.Binary _Foto;
		
		private string _CodUbigeo;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
		private EntityRef<TUbigeo> _TUbigeo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodInfoChanging(int value);
    partial void OnCodInfoChanged();
    partial void OnApellidosChanging(string value);
    partial void OnApellidosChanged();
    partial void OnNombresChanging(string value);
    partial void OnNombresChanged();
    partial void OnNacimientoChanging(System.Nullable<System.DateTime> value);
    partial void OnNacimientoChanged();
    partial void OnSexoChanging(System.Nullable<char> value);
    partial void OnSexoChanged();
    partial void OnEstadoCivilChanging(System.Nullable<char> value);
    partial void OnEstadoCivilChanged();
    partial void OnDNIChanging(string value);
    partial void OnDNIChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnInformacionChanging(string value);
    partial void OnInformacionChanged();
    partial void OnFotoChanging(System.Data.Linq.Binary value);
    partial void OnFotoChanged();
    partial void OnCodUbigeoChanging(string value);
    partial void OnCodUbigeoChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TInfo()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			this._TUbigeo = default(EntityRef<TUbigeo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodInfo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodInfo
		{
			get
			{
				return this._CodInfo;
			}
			set
			{
				if ((this._CodInfo != value))
				{
					this.OnCodInfoChanging(value);
					this.SendPropertyChanging();
					this._CodInfo = value;
					this.SendPropertyChanged("CodInfo");
					this.OnCodInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellidos", DbType="VarChar(100)")]
		public string Apellidos
		{
			get
			{
				return this._Apellidos;
			}
			set
			{
				if ((this._Apellidos != value))
				{
					this.OnApellidosChanging(value);
					this.SendPropertyChanging();
					this._Apellidos = value;
					this.SendPropertyChanged("Apellidos");
					this.OnApellidosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="VarChar(100)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this.OnNombresChanging(value);
					this.SendPropertyChanging();
					this._Nombres = value;
					this.SendPropertyChanged("Nombres");
					this.OnNombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> Nacimiento
		{
			get
			{
				return this._Nacimiento;
			}
			set
			{
				if ((this._Nacimiento != value))
				{
					this.OnNacimientoChanging(value);
					this.SendPropertyChanging();
					this._Nacimiento = value;
					this.SendPropertyChanged("Nacimiento");
					this.OnNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sexo", DbType="Char(1)")]
		public System.Nullable<char> Sexo
		{
			get
			{
				return this._Sexo;
			}
			set
			{
				if ((this._Sexo != value))
				{
					this.OnSexoChanging(value);
					this.SendPropertyChanging();
					this._Sexo = value;
					this.SendPropertyChanged("Sexo");
					this.OnSexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoCivil", DbType="Char(1)")]
		public System.Nullable<char> EstadoCivil
		{
			get
			{
				return this._EstadoCivil;
			}
			set
			{
				if ((this._EstadoCivil != value))
				{
					this.OnEstadoCivilChanging(value);
					this.SendPropertyChanging();
					this._EstadoCivil = value;
					this.SendPropertyChanged("EstadoCivil");
					this.OnEstadoCivilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNI", DbType="VarChar(20)")]
		public string DNI
		{
			get
			{
				return this._DNI;
			}
			set
			{
				if ((this._DNI != value))
				{
					this.OnDNIChanging(value);
					this.SendPropertyChanging();
					this._DNI = value;
					this.SendPropertyChanged("DNI");
					this.OnDNIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(200)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Informacion", DbType="VarChar(900)")]
		public string Informacion
		{
			get
			{
				return this._Informacion;
			}
			set
			{
				if ((this._Informacion != value))
				{
					this.OnInformacionChanging(value);
					this.SendPropertyChanging();
					this._Informacion = value;
					this.SendPropertyChanged("Informacion");
					this.OnInformacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUbigeo", DbType="VarChar(6)")]
		public string CodUbigeo
		{
			get
			{
				return this._CodUbigeo;
			}
			set
			{
				if ((this._CodUbigeo != value))
				{
					if (this._TUbigeo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodUbigeoChanging(value);
					this.SendPropertyChanging();
					this._CodUbigeo = value;
					this.SendPropertyChanged("CodUbigeo");
					this.OnCodUbigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TInfo", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TInfo.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TInfo.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUbigeo_TInfo", Storage="_TUbigeo", ThisKey="CodUbigeo", OtherKey="CodUbigeo", IsForeignKey=true)]
		public TUbigeo TUbigeo
		{
			get
			{
				return this._TUbigeo.Entity;
			}
			set
			{
				TUbigeo previousValue = this._TUbigeo.Entity;
				if (((previousValue != value) 
							|| (this._TUbigeo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TUbigeo.Entity = null;
						previousValue.TInfo.Remove(this);
					}
					this._TUbigeo.Entity = value;
					if ((value != null))
					{
						value.TInfo.Add(this);
						this._CodUbigeo = value.CodUbigeo;
					}
					else
					{
						this._CodUbigeo = default(string);
					}
					this.SendPropertyChanged("TUbigeo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRedSocial")]
	public partial class TRedSocial : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodRedSocial;
		
		private System.Nullable<char> _Vision;
		
		private string _Tipo;
		
		private string _Ruta;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodRedSocialChanging(int value);
    partial void OnCodRedSocialChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnRutaChanging(string value);
    partial void OnRutaChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TRedSocial()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodRedSocial", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodRedSocial
		{
			get
			{
				return this._CodRedSocial;
			}
			set
			{
				if ((this._CodRedSocial != value))
				{
					this.OnCodRedSocialChanging(value);
					this.SendPropertyChanging();
					this._CodRedSocial = value;
					this.SendPropertyChanged("CodRedSocial");
					this.OnCodRedSocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ruta", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Ruta
		{
			get
			{
				return this._Ruta;
			}
			set
			{
				if ((this._Ruta != value))
				{
					this.OnRutaChanging(value);
					this.SendPropertyChanging();
					this._Ruta = value;
					this.SendPropertyChanged("Ruta");
					this.OnRutaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TRedSocial", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TRedSocial.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TRedSocial.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TUbigeo")]
	public partial class TUbigeo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CodUbigeo;
		
		private string _CodDepartamento;
		
		private string _CodProvincia;
		
		private string _CodDistrito;
		
		private string _NomDepartamento;
		
		private string _NomProvincia;
		
		private string _NomDistrito;
		
		private EntitySet<TInfo> _TInfo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodUbigeoChanging(string value);
    partial void OnCodUbigeoChanged();
    partial void OnCodDepartamentoChanging(string value);
    partial void OnCodDepartamentoChanged();
    partial void OnCodProvinciaChanging(string value);
    partial void OnCodProvinciaChanged();
    partial void OnCodDistritoChanging(string value);
    partial void OnCodDistritoChanged();
    partial void OnNomDepartamentoChanging(string value);
    partial void OnNomDepartamentoChanged();
    partial void OnNomProvinciaChanging(string value);
    partial void OnNomProvinciaChanged();
    partial void OnNomDistritoChanging(string value);
    partial void OnNomDistritoChanged();
    #endregion
		
		public TUbigeo()
		{
			this._TInfo = new EntitySet<TInfo>(new Action<TInfo>(this.attach_TInfo), new Action<TInfo>(this.detach_TInfo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodUbigeo", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CodUbigeo
		{
			get
			{
				return this._CodUbigeo;
			}
			set
			{
				if ((this._CodUbigeo != value))
				{
					this.OnCodUbigeoChanging(value);
					this.SendPropertyChanging();
					this._CodUbigeo = value;
					this.SendPropertyChanged("CodUbigeo");
					this.OnCodUbigeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDepartamento", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CodDepartamento
		{
			get
			{
				return this._CodDepartamento;
			}
			set
			{
				if ((this._CodDepartamento != value))
				{
					this.OnCodDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._CodDepartamento = value;
					this.SendPropertyChanged("CodDepartamento");
					this.OnCodDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodProvincia", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CodProvincia
		{
			get
			{
				return this._CodProvincia;
			}
			set
			{
				if ((this._CodProvincia != value))
				{
					this.OnCodProvinciaChanging(value);
					this.SendPropertyChanging();
					this._CodProvincia = value;
					this.SendPropertyChanged("CodProvincia");
					this.OnCodProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodDistrito", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CodDistrito
		{
			get
			{
				return this._CodDistrito;
			}
			set
			{
				if ((this._CodDistrito != value))
				{
					this.OnCodDistritoChanging(value);
					this.SendPropertyChanging();
					this._CodDistrito = value;
					this.SendPropertyChanged("CodDistrito");
					this.OnCodDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomDepartamento", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NomDepartamento
		{
			get
			{
				return this._NomDepartamento;
			}
			set
			{
				if ((this._NomDepartamento != value))
				{
					this.OnNomDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._NomDepartamento = value;
					this.SendPropertyChanged("NomDepartamento");
					this.OnNomDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomProvincia", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NomProvincia
		{
			get
			{
				return this._NomProvincia;
			}
			set
			{
				if ((this._NomProvincia != value))
				{
					this.OnNomProvinciaChanging(value);
					this.SendPropertyChanging();
					this._NomProvincia = value;
					this.SendPropertyChanged("NomProvincia");
					this.OnNomProvinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomDistrito", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NomDistrito
		{
			get
			{
				return this._NomDistrito;
			}
			set
			{
				if ((this._NomDistrito != value))
				{
					this.OnNomDistritoChanging(value);
					this.SendPropertyChanging();
					this._NomDistrito = value;
					this.SendPropertyChanged("NomDistrito");
					this.OnNomDistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TUbigeo_TInfo", Storage="_TInfo", ThisKey="CodUbigeo", OtherKey="CodUbigeo")]
		public EntitySet<TInfo> TInfo
		{
			get
			{
				return this._TInfo;
			}
			set
			{
				this._TInfo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TInfo(TInfo entity)
		{
			this.SendPropertyChanging();
			entity.TUbigeo = this;
		}
		
		private void detach_TInfo(TInfo entity)
		{
			this.SendPropertyChanging();
			entity.TUbigeo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTrabajo")]
	public partial class TTrabajo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodTrabajo;
		
		private System.Nullable<char> _Vision;
		
		private string _Empresa;
		
		private string _Puesto;
		
		private string _Supervisor;
		
		private System.Nullable<System.DateTime> _Inicio;
		
		private System.Nullable<System.DateTime> _Fin;
		
		private int _CodCuenta;
		
		private EntityRef<TCuenta> _TCuenta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodTrabajoChanging(int value);
    partial void OnCodTrabajoChanged();
    partial void OnVisionChanging(System.Nullable<char> value);
    partial void OnVisionChanged();
    partial void OnEmpresaChanging(string value);
    partial void OnEmpresaChanged();
    partial void OnPuestoChanging(string value);
    partial void OnPuestoChanged();
    partial void OnSupervisorChanging(string value);
    partial void OnSupervisorChanged();
    partial void OnInicioChanging(System.Nullable<System.DateTime> value);
    partial void OnInicioChanged();
    partial void OnFinChanging(System.Nullable<System.DateTime> value);
    partial void OnFinChanged();
    partial void OnCodCuentaChanging(int value);
    partial void OnCodCuentaChanged();
    #endregion
		
		public TTrabajo()
		{
			this._TCuenta = default(EntityRef<TCuenta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodTrabajo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodTrabajo
		{
			get
			{
				return this._CodTrabajo;
			}
			set
			{
				if ((this._CodTrabajo != value))
				{
					this.OnCodTrabajoChanging(value);
					this.SendPropertyChanging();
					this._CodTrabajo = value;
					this.SendPropertyChanged("CodTrabajo");
					this.OnCodTrabajoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vision", DbType="Char(1)")]
		public System.Nullable<char> Vision
		{
			get
			{
				return this._Vision;
			}
			set
			{
				if ((this._Vision != value))
				{
					this.OnVisionChanging(value);
					this.SendPropertyChanging();
					this._Vision = value;
					this.SendPropertyChanged("Vision");
					this.OnVisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Empresa", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Empresa
		{
			get
			{
				return this._Empresa;
			}
			set
			{
				if ((this._Empresa != value))
				{
					this.OnEmpresaChanging(value);
					this.SendPropertyChanging();
					this._Empresa = value;
					this.SendPropertyChanged("Empresa");
					this.OnEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puesto", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Puesto
		{
			get
			{
				return this._Puesto;
			}
			set
			{
				if ((this._Puesto != value))
				{
					this.OnPuestoChanging(value);
					this.SendPropertyChanging();
					this._Puesto = value;
					this.SendPropertyChanged("Puesto");
					this.OnPuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Supervisor", DbType="VarChar(200)")]
		public string Supervisor
		{
			get
			{
				return this._Supervisor;
			}
			set
			{
				if ((this._Supervisor != value))
				{
					this.OnSupervisorChanging(value);
					this.SendPropertyChanging();
					this._Supervisor = value;
					this.SendPropertyChanged("Supervisor");
					this.OnSupervisorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inicio", DbType="Date")]
		public System.Nullable<System.DateTime> Inicio
		{
			get
			{
				return this._Inicio;
			}
			set
			{
				if ((this._Inicio != value))
				{
					this.OnInicioChanging(value);
					this.SendPropertyChanging();
					this._Inicio = value;
					this.SendPropertyChanged("Inicio");
					this.OnInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fin", DbType="Date")]
		public System.Nullable<System.DateTime> Fin
		{
			get
			{
				return this._Fin;
			}
			set
			{
				if ((this._Fin != value))
				{
					this.OnFinChanging(value);
					this.SendPropertyChanging();
					this._Fin = value;
					this.SendPropertyChanged("Fin");
					this.OnFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodCuenta", DbType="Int NOT NULL")]
		public int CodCuenta
		{
			get
			{
				return this._CodCuenta;
			}
			set
			{
				if ((this._CodCuenta != value))
				{
					if (this._TCuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodCuentaChanging(value);
					this.SendPropertyChanging();
					this._CodCuenta = value;
					this.SendPropertyChanged("CodCuenta");
					this.OnCodCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TCuenta_TTrabajo", Storage="_TCuenta", ThisKey="CodCuenta", OtherKey="CodCuenta", IsForeignKey=true)]
		public TCuenta TCuenta
		{
			get
			{
				return this._TCuenta.Entity;
			}
			set
			{
				TCuenta previousValue = this._TCuenta.Entity;
				if (((previousValue != value) 
							|| (this._TCuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TCuenta.Entity = null;
						previousValue.TTrabajo.Remove(this);
					}
					this._TCuenta.Entity = value;
					if ((value != null))
					{
						value.TTrabajo.Add(this);
						this._CodCuenta = value.CodCuenta;
					}
					else
					{
						this._CodCuenta = default(int);
					}
					this.SendPropertyChanged("TCuenta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
