//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteWeb.RefServicio3 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RefServicio3.ServicioCV3Soap")]
    public interface ServicioCV3Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonaGeneral", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PersonaGeneral();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PersonaGeneral", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> PersonaGeneralAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCV3SoapChannel : ClienteWeb.RefServicio3.ServicioCV3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCV3SoapClient : System.ServiceModel.ClientBase<ClienteWeb.RefServicio3.ServicioCV3Soap>, ClienteWeb.RefServicio3.ServicioCV3Soap {
        
        public ServicioCV3SoapClient() {
        }
        
        public ServicioCV3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCV3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCV3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCV3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet PersonaGeneral() {
            return base.Channel.PersonaGeneral();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> PersonaGeneralAsync() {
            return base.Channel.PersonaGeneralAsync();
        }
    }
}
